import {StyleSheet} from 'react-native';
import FONTS from '../../../constants/fonts';
import COLORS from '../../../constants/color';
export const styles = StyleSheet.create({
  mainContainer: {
    borderWidth: 1,
    borderColor: COLORS.HIGHLIGHT,
    borderRadius: 10,
    marginTop: 20,
    // marginBottom:10
  },
  ContainerView: {
    flex: 1,
    flexDirection: 'column',
    padding: 25,
    backgroundColor: COLORS.WHITE,
  },
  topContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // marginBottom: 25,
    // marginLeft: '5%',
    // marginRight: '5%',
    // paddingTop:8
  },
  programText: {
    fontSize: 14,
    // fontWeight: 'bold',
    marginLeft: '-63%',
    marginTop: 3,
    color: COLORS.BLACK,
    fontFamily: FONTS.BOLD,
  },
  topBack: {height: 20, width: 20, marginTop: 4},
  descriptionText: {
    fontSize: 14,
    color: COLORS.BLACK,
    fontFamily: FONTS.REGULAR,
  },
  topText: {
    fontSize: 16,
    // fontWeight: '500',
    // color: '#313131',
    marginBottom: 10,
    color: COLORS.BLACK,
    fontFamily: FONTS.MEDIUM,
  },
  textViewStyel: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  nextButton: {
    marginTop: 20,
    height: 40,
    borderWidth: 1,
    borderRadius: 10,
    // backgroundColor: '#f8f9fa',
    borderColor: COLORS.HIGHLIGHT,
  },
  Button: {
    justifyContent: 'center',
    marginTop: 20,
    height: 40,
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: COLORS.PRIMARY,
    borderColor: COLORS.PRIMARY,
  },
  nextImage: {marginLeft: '45%', marginTop: 5},
  nextButtonText: {
    marginLeft: 10,
    // fontWeight: '400',
    fontSize: 16,
    color: COLORS.BLACK,
    fontFamily: FONTS.REGULAR
  },
  nextButtonView: {flexDirection: 'row', marginTop: 8, marginLeft: 15},
  ButtonView: {justifyContent: 'center'},
  textContainer: {flexDirection: 'column', marginTop: 10},
  textMode: {fontSize: 12, fontWeight: '400', color: COLORS.BLACK,  fontFamily: FONTS.REGULAR,},
  textOnline: {fontSize: 14, fontWeight: '500', color: COLORS.BLACK,  fontFamily: FONTS.MEDIUM,},
  timeTextStyle: {
    fontSize: 14,
    fontFamily: FONTS.MEDIUM,
    color: COLORS.BLACK,
  },
  viewAvailablity: {flexDirection: 'column', marginTop: 10, marginRight: '40%'},
  container: {
    flex: 1,
    paddingTop: 22,
  },
  item: {
    //   height:"50%",
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
    paddingVertical: 5,
    marginTop: 20,
  },
  sequence: {
    // paddingHorizontal: 16,
    fontSize: 16,
    // fontWeight: '500',
    color: COLORS.BLACK,
    fontFamily: FONTS.MEDIUM,
  },
  tabsContainerStyle: {
    borderColor: COLORS.BLACK,
  },
  tabStyle: {
    marginRight: '50%',
    borderColor: 'white',
  },
  activeTabStyle: {
    backgroundColor: 'white',
    marginTop: 2,
    borderColor: 'black',
    borderTopColor: 'white',
    borderEndColor: 'white',
    borderStartColor: 'white',
  },
  tabTextStyle: {color: COLORS.BLACK, fontFamily: FONTS.REGULAR, fontSize: 14},
  activeTabTextStyle: {color: COLORS.BLACK,  fontFamily: FONTS.BOLD, },
  lineView: {height: 1, backgroundColor: COLORS.HIGHLIGHT},
  image: {
    width: 80,
    height: 80,
    resizeMode: 'cover',
    marginLeft: 10,
    marginTop: -10,
    // marginBottom: 10,
  },
  details: {
    flex: 1,
    // marginHorizontal: 16,
    marginLeft: 10,
    // flexWrap:"wrap"
    marginTop: -25,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  sessionDuration: {
    fontSize: 12,
    color: COLORS.BLACK,
    fontFamily: FONTS.REGULAR,
  },
  date: {
    fontSize: 12,
    color: COLORS.BLACK,
    // fontWeight: '400',
    marginLeft: 20,
    fontFamily: FONTS.REGULAR,
  },
  scheduledTime: {
    fontSize: 12,
    color: COLORS.BLACK,
    fontFamily: FONTS.REGULAR,
  },
  incomingSession: {
    marginLeft: 5,
    // fontWeight: '500',
    fontSize: 14,
    color: COLORS.BLACK,
    fontFamily: FONTS.SEMI_BOLD,
  },
  incomingTime: {
    marginLeft: '4%',
    color: COLORS.BLACK,
    fontFamily: FONTS.SEMI_BOLD,
    fontSize: 14,
  },
  program: {marginBottom: 5, color: COLORS.BLACK, fontFamily: FONTS.REGULAR},
  incomingDate: {
    marginLeft: '19%',
    // fontWeight: '500',
    color: COLORS.BLACK,
    fontFamily: FONTS.MEDIUM,
    fontSize: 14,
  },
  textStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginLeft: 10,
    marginRight: 20,
  },
  programDescription: {color: COLORS.BLACK, 
    fontFamily: FONTS.REGULAR,
    fontSize:14
  },
});
