export const registerUser = 'mentor/register';
export const LoginUrl = 'auth/login';
export const forgotPasswordUrl = 'auth/forgot-password?email=';
export const resendOtpUrl = 'auth/resendotp';
export const confirmOtpUrl = 'auth/otpverify';
export const resetPasswordUrl = 'auth/create-password';
export const updateMentorUrl = 'mentor/update';
export const updateProgramUrl = 'mentorship/update';
export const getCategoryurl = 'mentorship/getAll-mentorship';
export const getmentorsurl = 'mentor/getAll-users'
export const addProgram = 'mentorship/add';
export const addSessionurl = 'mentorship/dayWise';
export const fetchProfileurl = 'mentor/getUser';
export const ProgramListurl = 'mentorship/getMentorshipById';
export const ProgramDetailsurl = 'mentorship/getwholeProgramdetail';
export const baseURL = 'http://54.190.192.105:9192/';
export const listurl = 'mentorship/getallProgramDropdown';
