import {StyleSheet} from 'react-native';
import {black} from 'react-native-paper/lib/typescript/styles/themes/v2/colors';
import {RFPercentage, RFValue} from 'react-native-responsive-fontsize';
import {globalColors} from '../../theme/globalColors';
import {globalFonts} from '../../theme/globalFonts';
import COLORS from "../../constants/color"
export const styles = StyleSheet.create({
  icons: {
    height: RFValue(15),
    width: RFValue(15),
    marginTop: RFValue(3),
  },
  button: {
    backgroundColor: '#FE4D4D',
    height: RFValue(45),
    width: '100%',
    marginTop: RFValue(20),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: RFValue(10),
  },
  backImg: {height: RFValue(30), width: RFValue(30)},
  back: {
    height: RFValue(40),
    width: RFValue(40),
    borderColor: globalColors.white,
    margin: RFValue(20),
    position: 'absolute',
    left: 0,
    top: RFValue(18),
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageBack: {height: RFPercentage(50)},
  imageBackView: {flex: 1, alignItems: 'center', marginTop: RFValue(10)},
  logoImage: {height: RFPercentage(40), width: RFPercentage(40)},
  bottomView: {
    flex: 2,
    backgroundColor: '#ffffff',
    bottom: RFValue(80),
    borderTopStartRadius: RFValue(40),
    borderTopEndRadius: RFValue(40),
  },
  signInText: {
    fontSize: RFValue(30),
    // marginVertical: RFValue(30),
    fontWeight: 'bold',
    marginBottom: 1,
    color: 'black',
    marginTop: 20,
  },
  inputLbl: {
    marginLeft: RFValue(10),
    color: '#FE4D4D',
  },
  inputStyles: {
    height: RFValue(50),
    width: '100%',
    borderRadius: RFValue(10),
    marginTop: RFValue(15),
    borderWidth: 0,
    fontFamily: globalFonts.regular,
  },
  forgotpass: {
    alignSelf: 'flex-end',
    color: '#FE4D4D',
    marginBottom: 10,
    fontFamily: globalFonts.regular,
    fontSize: RFValue(16),
  },
  buttonText: {
    fontWeight: 'bold',
    fontSize: RFValue(18),
    color: globalColors.white,
    fontFamily: globalFonts.regular,
  },
  accountText: {
    color: globalColors.grey,
    fontFamily: globalFonts.regular,
    fontSize: RFValue(14),
  },
  signUpText: {
    color: 'black',
    fontSize: RFValue(14),
    marginHorizontal: RFValue(2),
  },
  textInputView: {marginHorizontal: RFValue(15), paddingVertical: RFValue(15)},
  signUpView: {
    flexDirection: 'row',
    marginTop: RFValue(10),
    paddingVertical: 10,
    alignSelf: 'flex-start',
    marginLeft: 10,
  },
  signUpbottomView: {
    flexDirection: 'row',
    marginTop: RFValue(10),
    paddingVertical: 10,
    alignSelf: 'center',
    marginLeft: 10,
  },
  Input: {
    height: 40,
    borderWidth: 1,
    margin: 12,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    borderTopRightRadius: 10,
    marginBottom: 30,
    padding: 10,
    borderColor: 'black',
  },
  SectionStyle: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 0.5,
    borderColor: '#000',
    height: 40,
    borderRadius: 5,
    margin: 10,
  },
  ImageStyle: {
    padding: 10,
    margin: 5,
    height: 25,
    width: 25,
    resizeMode: 'stretch',
    alignItems: 'center',
  },
  InputView: {
    marginHorizontal: 5,
    marginTop: 25,
    borderWidth: 1,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: 10,
  },
  Inputstyle: {
    width: '90%',
    marginVertical: 2,
    height: 40,
    color: 'black',
    fontSize: 15,
  },
  InputImageStyle: {
    width: 25,
    height: 25,
  },
  container: {flex: 1, backgroundColor: '#fff'},
  mainImage: {
    alignItems:"center",
    marginTop: '15%', 
    marginLeft: '10%', 
    marginBottom: '10%',
    marginRight:'10%'  },
  signUpTextView: {flex: 2, marginLeft: '10%'},
  signupText: {
    color: COLORS.BLACK,
    fontWeight: 'bold',
    fontSize: 30,
    marginBottom: 5,
  },
  text: {color: COLORS.GREY, fontSize:13},
  buttonView: {marginTop: 15, flexDirection: 'row'},
  mentorButton: {
    backgroundColor: 'black',
    height: 35,
    width: '25%',
    borderBottomLeftRadius: 20,
    borderTopLeftRadius: 20,
  },
  mentorButton1: {
    backgroundColor: '#DDDDDD',
                  height: 35,
                  width: '25%',
                  borderBottomLeftRadius: 20,
                  borderTopLeftRadius: 20,
  },
  menteeButton: {
    backgroundColor: '#DDDDDD',
    height: 35,
    width: '25%',
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
  },
  menteeButton1: {
    backgroundColor: 'black',
    height: 35,
    width: '25%',
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
  },
  menteeText: {color: 'black', alignSelf: 'center', padding: 5},
  menteeText1: {color: 'white', alignSelf: 'center', padding: 5},
  mentorText: {color: 'white', alignSelf: 'center', padding: 5},
  mentorText1: {color: 'black', alignSelf: 'center', padding: 5},
  referalView: {
    flex: 3,
    marginTop: '7%',
    marginLeft: '10%',
    marginRight: '10%',
    marginBottom:15
    // justifyContent:"center",
    // alignItems:"center"
  },
  inputTextView: {
    flex: 3,
    // marginTop: '5%',
    marginLeft: '10%',
    marginRight: '10%',
    marginBottom:"3%",
  },
  inputField: {
    borderWidth: 1,
    borderRadius: 10,
    width: '100%',
    color: 'black',
    height: 45,
  },
  imageView: {
    alignSelf: 'flex-end',
    marginTop: 9,
    marginRight: '10%',
    position: 'absolute',
  },
  image: {height: 20, width: 20, marginTop: 10},
  bottomText: {color: COLORS.GREY, marginTop: '8%'},
  ContinueButton: {
    flex: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 35,
    marginLeft: '10%',
    marginRight: '10%',
    backgroundColor: '#FE4D4D',
    height: 50,
    width: '80%',
    borderRadius: 10,
  },
  logInText: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: '-5%',
    marginBottom: 20,
  },
  joinText: {color: 'black'},
  login: {color: 'black', fontWeight: '600'},
});