import {StyleSheet} from 'react-native';
import {RFPercentage, RFValue} from 'react-native-responsive-fontsize';
// import { globalFonts } from '../../theme/globalFonts';
import {globalColors} from '../../theme/globalColors';
export const styles = StyleSheet.create({
  icons: {
    height: RFValue(15),
    width: RFValue(15),
    marginTop: RFValue(3),
  },
  forgetPassTxt: {
    marginBottom: RFValue(2),
    paddingHorizontal: 30,
    marginLeft: -20,
  },
  button: {
    backgroundColor: '#FE4D4D',
    height: RFValue(45),
    width: '100%',
    marginTop: RFValue(30),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: RFValue(10),
  },
  backImg: {height: RFValue(30), width: RFValue(30)},
  back: {
    height: RFValue(40),
    width: RFValue(40),
    borderColor: globalColors.white,
    margin: RFValue(20),
    position: 'absolute',
    left: 0,
    top: RFValue(18),
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageBack: {height: RFPercentage(55), marginTop: 50},
  imageBackView: {flex: 1, alignItems: 'center', marginTop: RFValue(70)},
  logoImage: {height: RFPercentage(38), width: RFPercentage(38)},
  bottomView: {
    flex: 2,
    backgroundColor: '#ffffff',
    bottom: RFValue(80),
    borderTopStartRadius: RFValue(40),
    borderTopEndRadius: RFValue(40),
  },
  signInText: {
    fontSize: RFValue(35),
    fontWeight: 'bold',
    // marginVertical: RFValue(5),
    color: 'black',
    paddingHorizontal: 5,
    // marginLeft:-30
  },
  inputLbl: {
    marginLeft: RFValue(10),
    color: '#27316F',
  },
  inputStyles: {
    height: RFValue(50),
    width: '100%',
    borderRadius: RFValue(10),
    marginTop: RFValue(15),
    borderWidth: 0,
    // fontFamily: globalFonts.regular,
  },
  forgotpass: {
    alignSelf: 'flex-end',
    color: '#27316F',
    marginBottom: 10,
    // fontFamily: globalFonts.regular,
    fontSize: RFValue(16),
  },
  buttonText: {
    fontSize: RFValue(18),
    color: globalColors.white,
    // fontFamily: globalFonts.regular
    fontWeight: 'bold',
  },
  accountText: {
    color: globalColors.grey,
    // fontFamily: globalFonts.regular,
    fontSize: RFValue(14),
  },
  signUpText: {color: globalColors.primaryTheme, fontSize: RFValue(14)},
  textInputView: {marginHorizontal: RFValue(15), paddingVertical: RFValue(15)},
  signUpView: {
    flexDirection: 'row',
    marginTop: RFValue(15),
    alignSelf: 'center',
  },
  SectionStyle: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 0.5,
    borderColor: '#000',
    height: 40,
    borderRadius: 5,
    margin: 10,
  },
  ImageStyle: {
    padding: 10,
    margin: 5,
    height: 25,
    width: 25,
    resizeMode: 'stretch',
    alignItems: 'center',
  },
  InputView: {
    marginHorizontal: 5,
    marginTop: 25,
    borderWidth: 1,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: 10,
  },
  Inputstyle: {
    width: '90%',
    marginVertical: 2,
    height: 40,
    color: 'black',
    fontSize: 15,
  },
  InputImageStyle: {
    width: 25,
    height: 25,
  },
  container: {flex: 1, backgroundColor: 'white'},
  resetImageView: {alignSelf: 'center', marginTop: '20%'},
  resetView: {
    flex: 2,
    marginTop: '10%',
    marginLeft: '10%',
    marginBottom: '5%',
  },
  resetText: {fontWeight: 'bold', fontSize: 36, color: 'black'},
  passwordText: {
    fontWeight: 'bold',
    fontSize: 36,
    color: 'black',
    marginTop: -10,
  },
  newPasswordText: {color: 'grey', marginTop: 2},
  prePasswordText: {color: 'black', marginTop: 2},
  inputfieldView: {
    flex: 3,
    marginTop: '5%',
    marginLeft: '10%',
    marginRight: '10%',
    marginBottom:"5%",
    // justifyContent:"center",
    // alignItems:"center"
  },
  inputPassword: {
    borderWidth: 1,
    borderRadius: 10,
    width: '100%',
    color: 'black',
    height: 45,
  },
  eyeIconView: {
    alignSelf: 'flex-end',
    marginTop: 5,
    marginRight: '10%',
    position: 'absolute',
  },
  eyeIconImage: {height: 20, width: 20, marginTop: 15},
  CharacterText: {
    color: 'black',
    fontWeight: 'normal',
    fontSize: 14,
    marginTop: 5,
  },
  viewInputConfirm: {
    flex: 3,
    marginTop: '1%',
    marginLeft: '10%',
    marginRight: '10%',
  },
  inputConfirm: {
    borderWidth: 1,
    borderRadius: 10,
    width: '100%',
    color: 'black',
    height: 45,
  },
  lockImage: {height: 20, width: 20, marginTop: 15},
  matchText: {
    color: 'black',
    fontWeight: 'normal',
    fontSize: 14,
    marginTop: 5,
  },
  saveButton: {
    // flex: 4,
    // justifyContent: 'center',
    // alignItems: 'center',
    // marginTop: 20,
    // marginBottom: 35,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 35,
    marginBottom: 35,
    marginLeft: '10%',
    marginRight: '10%',
    backgroundColor: '#FE4D4D',
    height: 50,
    width: '80%',
    borderRadius: 10,
  },
  viewLockImage: {
    alignSelf: 'flex-end',
    marginTop: 5,
    marginRight: '10%',
    position: 'absolute',
  },
});